const std = @import("std");
pub const theme_file = struct { file_name: []const u8, json: []const u8, cbor: ?[]const u8 = null };

pub const theme_files = [_]theme_file{

    // dark themes

    THEME("default.json"),
    THEME("themes/1984-color-theme.json"),
    THEME("themes/1984-cyberpunk-color-theme.json"),
    THEME("themes/1984-orwell-color-theme.json"),
    THEME("theme/cobalt2.json"),
    THEME("themes/oldschool-gray-color-theme.json"),
    THEME("themes/oldschool-terminal-green.json"),
    THEME("themes/Turbo Colors-color-theme.json"),
    THEME("extensions/theme-tomorrow-night-blue/themes/tomorrow-night-blue-color-theme.json"),
    THEME("extensions/theme-monokai/themes/monokai-color-theme.json"),
    THEME("extensions/theme-solarized-dark/themes/solarized-dark-color-theme.json"),
    THEME("extensions/theme-kimbie-dark/themes/kimbie-dark-color-theme.json"),
    THEME("themes/CRT-64-color-theme.json"),
    THEME("themes/CRT-Amber-color-theme.json"),
    THEME("themes/CRT-Gray-color-theme.json"),
    THEME("themes/CRT-Green-color-theme.json"),
    THEME("themes/gruvbox-dark-hard.json"),
    THEME("themes/gruvbox-dark-medium.json"),
    THEME("themes/gruvbox-dark-soft.json"),
    THEME("themes/gruvbox-material-dark.json"),
    THEME("themes/tokyo-night-storm-color-theme.json"),
    THEME("themes/tokyo-night-color-theme.json"),
    THEME("ayu-dark.json"),
    THEME("ayu-dark-bordered.json"),
    THEME("ayu-mirage.json"),
    THEME("ayu-mirage-bordered.json"),
    THEME("extensions/theme-defaults/themes/dark_vs.json"),
    THEME("extensions/theme-defaults/themes/dark_plus.json"),
    THEME("extensions/theme-defaults/themes/dark_modern.json"),
    THEME("themes/OneDark-Pro.json"),
    THEME("themes/rose-pine-color-theme.json"),
    THEME("themes/rose-pine-no-italics-color-theme.json"),
    THEME("themes/rose-pine-moon-color-theme.json"),
    THEME("themes/rose-pine-moon-no-italics-color-theme.json"),
    THEME("themes/adwaita-dark.json"),
    THEME("themes/everforest-dark.json"),
    THEME("themes/nord-color-theme.json"),
    THEME("themes/frappe.json"),
    THEME("themes/macchiato.json"),
    THEME("themes/mocha.json"),
    THEME("themes/mellow.json"),
    THEME("themes/Hypersubatomic-color-theme.json"),

    // zenbones collection dark

    THEME("extras/vscode/themes/zenbones_dark_default.json"),
    THEME("extras/vscode/themes/zenbones_dark_stark.json"),
    THEME("extras/vscode/themes/zenbones_dark_warm.json"),
    THEME("extras/vscode/themes/duckbones_default.json"),
    THEME("extras/vscode/themes/duckbones_stark.json"),
    THEME("extras/vscode/themes/duckbones_warm.json"),
    THEME("extras/vscode/themes/forestbones_dark_default.json"),
    THEME("extras/vscode/themes/forestbones_dark_stark.json"),
    THEME("extras/vscode/themes/forestbones_dark_warm.json"),
    THEME("extras/vscode/themes/kanagawabones_default.json"),
    THEME("extras/vscode/themes/kanagawabones_stark.json"),
    THEME("extras/vscode/themes/kanagawabones_warm.json"),
    THEME("extras/vscode/themes/neobones_dark_default.json"),
    THEME("extras/vscode/themes/neobones_dark_stark.json"),
    THEME("extras/vscode/themes/neobones_dark_warm.json"),
    THEME("extras/vscode/themes/nordbones_default.json"),
    THEME("extras/vscode/themes/nordbones_stark.json"),
    THEME("extras/vscode/themes/nordbones_warm.json"),
    THEME("extras/vscode/themes/rosebones_dark_default.json"),
    THEME("extras/vscode/themes/rosebones_dark_stark.json"),
    THEME("extras/vscode/themes/rosebones_dark_warm.json"),
    THEME("extras/vscode/themes/seoulbones_dark_default.json"),
    THEME("extras/vscode/themes/seoulbones_dark_stark.json"),
    THEME("extras/vscode/themes/seoulbones_dark_warm.json"),
    THEME("extras/vscode/themes/tokyobones_dark_default.json"),
    THEME("extras/vscode/themes/tokyobones_dark_stark.json"),
    THEME("extras/vscode/themes/tokyobones_dark_warm.json"),
    THEME("extras/vscode/themes/zenburned_default.json"),
    THEME("extras/vscode/themes/zenburned_stark.json"),
    THEME("extras/vscode/themes/zenburned_warm.json"),
    THEME("extras/vscode/themes/zenwritten_dark_default.json"),
    THEME("extras/vscode/themes/zenwritten_dark_stark.json"),
    THEME("extras/vscode/themes/zenwritten_dark_warm.json"),

    // light themes

    THEME("themes/1984-light-color-theme.json"),
    THEME("extensions/theme-solarized-light/themes/solarized-light-color-theme.json"),
    THEME("themes/CRT-Paper-color-theme.json"),
    THEME("themes/gruvbox-light-hard.json"),
    THEME("themes/gruvbox-light-medium.json"),
    THEME("themes/gruvbox-light-soft.json"),
    THEME("themes/gruvbox-material-light.json"),
    THEME("extensions/theme-defaults/themes/light_vs.json"),
    THEME("extensions/theme-defaults/themes/light_plus.json"),
    THEME("extensions/theme-defaults/themes/light_modern.json"),
    THEME("themes/tokyo-night-light-color-theme.json"),
    THEME("ayu-light.json"),
    THEME("ayu-light-bordered.json"),
    THEME("themes/rose-pine-dawn-color-theme.json"),
    THEME("themes/adwaita-light.json"),
    THEME("themes/everforest-light.json"),
    THEME("themes/latte.json"),

    // zenbones collection light

    THEME("extras/vscode/themes/zenbones_light_bright.json"),
    THEME("extras/vscode/themes/zenbones_light_default.json"),
    THEME("extras/vscode/themes/zenbones_light_dim.json"),
    THEME("extras/vscode/themes/forestbones_light_bright.json"),
    THEME("extras/vscode/themes/forestbones_light_default.json"),
    THEME("extras/vscode/themes/forestbones_light_dim.json"),
    THEME("extras/vscode/themes/neobones_light_bright.json"),
    THEME("extras/vscode/themes/neobones_light_default.json"),
    THEME("extras/vscode/themes/neobones_light_dim.json"),
    THEME("extras/vscode/themes/rosebones_light_bright.json"),
    THEME("extras/vscode/themes/rosebones_light_default.json"),
    THEME("extras/vscode/themes/rosebones_light_dim.json"),
    THEME("extras/vscode/themes/seoulbones_light_bright.json"),
    THEME("extras/vscode/themes/seoulbones_light_default.json"),
    THEME("extras/vscode/themes/seoulbones_light_dim.json"),
    THEME("extras/vscode/themes/tokyobones_light_bright.json"),
    THEME("extras/vscode/themes/tokyobones_light_default.json"),
    THEME("extras/vscode/themes/tokyobones_light_dim.json"),
    THEME("extras/vscode/themes/vimbones_bright.json"),
    THEME("extras/vscode/themes/vimbones_default.json"),
    THEME("extras/vscode/themes/vimbones_dim.json"),
    THEME("extras/vscode/themes/zenwritten_light_bright.json"),
    THEME("extras/vscode/themes/zenwritten_light_default.json"),
    THEME("extras/vscode/themes/zenwritten_light_dim.json"),
};

fn THEME(comptime file_path: []const u8) theme_file {
    @setEvalBranchQuota(10000);
    return .{ .file_name = std.fs.path.basename(file_path), .json = @embedFile(file_path) };
}
