const std = @import("std");
pub const theme_file = struct { file_name: []const u8, json: []const u8, cbor: ?[]const u8 = null };

pub const theme_files = [_]theme_file{

    // dark themes

    THEME("default.json"),
    THEME("themes/1984-color-theme.json"),
    THEME("themes/1984-cyberpunk-color-theme.json"),
    THEME("themes/1984-orwell-color-theme.json"),
    THEME("theme/cobalt2.json"),
    THEME("themes/oldschool-gray-color-theme.json"),
    THEME("themes/oldschool-terminal-green.json"),
    THEME("themes/Turbo Colors-color-theme.json"),
    THEME("extensions/theme-tomorrow-night-blue/themes/tomorrow-night-blue-color-theme.json"),
    THEME("extensions/theme-monokai/themes/monokai-color-theme.json"),
    THEME("extensions/theme-solarized-dark/themes/solarized-dark-color-theme.json"),
    THEME("extensions/theme-kimbie-dark/themes/kimbie-dark-color-theme.json"),
    THEME("themes/CRT-64-color-theme.json"),
    THEME("themes/CRT-Amber-color-theme.json"),
    THEME("themes/CRT-Gray-color-theme.json"),
    THEME("themes/CRT-Green-color-theme.json"),
    THEME("themes/gruvbox-dark-hard.json"),
    THEME("themes/gruvbox-dark-medium.json"),
    THEME("themes/gruvbox-dark-soft.json"),
    THEME("themes/gruvbox-material-dark.json"),
    THEME("themes/tokyo-night-storm-color-theme.json"),
    THEME("themes/tokyo-night-color-theme.json"),
    THEME("ayu-dark.json"),
    THEME("ayu-dark-bordered.json"),
    THEME("ayu-mirage.json"),
    THEME("ayu-mirage-bordered.json"),
    THEME("extensions/theme-defaults/themes/dark_vs.json"),
    THEME("extensions/theme-defaults/themes/dark_plus.json"),
    THEME("extensions/theme-defaults/themes/dark_modern.json"),
    THEME("themes/OneDark-Pro.json"),
    THEME("themes/rose-pine-color-theme.json"),
    THEME("themes/rose-pine-no-italics-color-theme.json"),
    THEME("themes/rose-pine-moon-color-theme.json"),
    THEME("themes/rose-pine-moon-no-italics-color-theme.json"),
    THEME("themes/adwaita-dark.json"),
    THEME("themes/everforest-dark.json"),
    THEME("themes/nord-color-theme.json"),
    THEME("themes/frappe.json"),
    THEME("themes/macchiato.json"),
    THEME("themes/mocha.json"),
    THEME("themes/mellow.json"),
    THEME("themes/Hypersubatomic-color-theme.json"),
    THEME("themes/kanagawa-wave-color-theme.json"),
    THEME("themes/kanagawa-dragon-color-theme.json"),
    THEME("themes/kanagawa-lotus-color-theme.json"),

    // base16 collection dark

    THEME("themes/3024-dark.json"),
    THEME("themes/apathy-dark.json"),
    THEME("themes/ashes-dark.json"),
    THEME("themes/atelierdune-dark.json"),
    THEME("themes/atelierforest-dark.json"),
    THEME("themes/atelierheath-dark.json"),
    THEME("themes/atelierlakeside-dark.json"),
    THEME("themes/atelierseaside-dark.json"),
    THEME("themes/bespin-dark.json"),
    THEME("themes/brewer-dark.json"),
    THEME("themes/bright-dark.json"),
    THEME("themes/chalk-dark.json"),
    THEME("themes/codeschool-dark.json"),
    THEME("themes/colors-dark.json"),
    THEME("themes/default-dark.json"),
    THEME("themes/eighties-dark.json"),
    THEME("themes/embers-dark.json"),
    THEME("themes/flat-dark.json"),
    THEME("themes/google-dark.json"),
    THEME("themes/grayscale-dark.json"),
    THEME("themes/greenscreen-dark.json"),
    THEME("themes/harmonic16-dark.json"),
    THEME("themes/isotope-dark.json"),
    THEME("themes/londontube-dark.json"),
    THEME("themes/marrakesh-dark.json"),
    THEME("themes/mocha-dark.json"),
    THEME("themes/monokai-dark.json"),
    THEME("themes/ocean-dark.json"),
    THEME("themes/oceanicnext-dark.json"),
    THEME("themes/paraiso-dark.json"),
    THEME("themes/pop-dark.json"),
    THEME("themes/railscasts-dark.json"),
    THEME("themes/shapeshifter-dark.json"),
    THEME("themes/solarized-dark.json"),
    THEME("themes/summerfruit-dark.json"),
    THEME("themes/tomorrow-dark.json"),
    THEME("themes/twilight-dark.json"),
    THEME("themes/unikitty-dark.json"),
    THEME("themes/woodland-dark.json"),

    // zenbones collection dark

    THEME("extras/vscode/themes/zenbones_dark_default.json"),
    THEME("extras/vscode/themes/zenbones_dark_stark.json"),
    THEME("extras/vscode/themes/zenbones_dark_warm.json"),
    THEME("extras/vscode/themes/duckbones_default.json"),
    THEME("extras/vscode/themes/duckbones_stark.json"),
    THEME("extras/vscode/themes/duckbones_warm.json"),
    THEME("extras/vscode/themes/forestbones_dark_default.json"),
    THEME("extras/vscode/themes/forestbones_dark_stark.json"),
    THEME("extras/vscode/themes/forestbones_dark_warm.json"),
    THEME("extras/vscode/themes/kanagawabones_default.json"),
    THEME("extras/vscode/themes/kanagawabones_stark.json"),
    THEME("extras/vscode/themes/kanagawabones_warm.json"),
    THEME("extras/vscode/themes/neobones_dark_default.json"),
    THEME("extras/vscode/themes/neobones_dark_stark.json"),
    THEME("extras/vscode/themes/neobones_dark_warm.json"),
    THEME("extras/vscode/themes/nordbones_default.json"),
    THEME("extras/vscode/themes/nordbones_stark.json"),
    THEME("extras/vscode/themes/nordbones_warm.json"),
    THEME("extras/vscode/themes/rosebones_dark_default.json"),
    THEME("extras/vscode/themes/rosebones_dark_stark.json"),
    THEME("extras/vscode/themes/rosebones_dark_warm.json"),
    THEME("extras/vscode/themes/seoulbones_dark_default.json"),
    THEME("extras/vscode/themes/seoulbones_dark_stark.json"),
    THEME("extras/vscode/themes/seoulbones_dark_warm.json"),
    THEME("extras/vscode/themes/tokyobones_dark_default.json"),
    THEME("extras/vscode/themes/tokyobones_dark_stark.json"),
    THEME("extras/vscode/themes/tokyobones_dark_warm.json"),
    THEME("extras/vscode/themes/zenburned_default.json"),
    THEME("extras/vscode/themes/zenburned_stark.json"),
    THEME("extras/vscode/themes/zenburned_warm.json"),
    THEME("extras/vscode/themes/zenwritten_dark_default.json"),
    THEME("extras/vscode/themes/zenwritten_dark_stark.json"),
    THEME("extras/vscode/themes/zenwritten_dark_warm.json"),

    // light themes

    THEME("themes/1984-light-color-theme.json"),
    THEME("extensions/theme-solarized-light/themes/solarized-light-color-theme.json"),
    THEME("themes/CRT-Paper-color-theme.json"),
    THEME("themes/gruvbox-light-hard.json"),
    THEME("themes/gruvbox-light-medium.json"),
    THEME("themes/gruvbox-light-soft.json"),
    THEME("themes/gruvbox-material-light.json"),
    THEME("extensions/theme-defaults/themes/light_vs.json"),
    THEME("extensions/theme-defaults/themes/light_plus.json"),
    THEME("extensions/theme-defaults/themes/light_modern.json"),
    THEME("themes/tokyo-night-light-color-theme.json"),
    THEME("ayu-light.json"),
    THEME("ayu-light-bordered.json"),
    THEME("themes/rose-pine-dawn-color-theme.json"),
    THEME("themes/adwaita-light.json"),
    THEME("themes/everforest-light.json"),
    THEME("themes/latte.json"),

    // base16 collection light

    THEME("themes/3024-light.json"),
    THEME("themes/apathy-light.json"),
    THEME("themes/ashes-light.json"),
    THEME("themes/atelierdune-light.json"),
    THEME("themes/atelierforest-light.json"),
    THEME("themes/atelierheath-light.json"),
    THEME("themes/atelierlakeside-light.json"),
    THEME("themes/atelierseaside-light.json"),
    THEME("themes/bespin-light.json"),
    THEME("themes/brewer-light.json"),
    THEME("themes/bright-light.json"),
    THEME("themes/chalk-light.json"),
    THEME("themes/codeschool-light.json"),
    THEME("themes/colors-light.json"),
    THEME("themes/default-light.json"),
    THEME("themes/eighties-light.json"),
    THEME("themes/embers-light.json"),
    THEME("themes/flat-light.json"),
    THEME("themes/google-light.json"),
    THEME("themes/grayscale-light.json"),
    THEME("themes/greenscreen-light.json"),
    THEME("themes/harmonic16-light.json"),
    THEME("themes/isotope-light.json"),
    THEME("themes/londontube-light.json"),
    THEME("themes/marrakesh-light.json"),
    THEME("themes/mocha-light.json"),
    THEME("themes/monokai-light.json"),
    THEME("themes/ocean-light.json"),
    THEME("themes/paraiso-light.json"),
    THEME("themes/pop-light.json"),
    THEME("themes/railscasts-light.json"),
    THEME("themes/shapeshifter-light.json"),
    THEME("themes/solarized-light.json"),
    THEME("themes/summerfruit-light.json"),
    THEME("themes/tomorrow-light.json"),
    THEME("themes/twilight-light.json"),
    THEME("themes/unikitty-light.json"),

    // zenbones collection light

    THEME("extras/vscode/themes/zenbones_light_bright.json"),
    THEME("extras/vscode/themes/zenbones_light_default.json"),
    THEME("extras/vscode/themes/zenbones_light_dim.json"),
    THEME("extras/vscode/themes/forestbones_light_bright.json"),
    THEME("extras/vscode/themes/forestbones_light_default.json"),
    THEME("extras/vscode/themes/forestbones_light_dim.json"),
    THEME("extras/vscode/themes/neobones_light_bright.json"),
    THEME("extras/vscode/themes/neobones_light_default.json"),
    THEME("extras/vscode/themes/neobones_light_dim.json"),
    THEME("extras/vscode/themes/rosebones_light_bright.json"),
    THEME("extras/vscode/themes/rosebones_light_default.json"),
    THEME("extras/vscode/themes/rosebones_light_dim.json"),
    THEME("extras/vscode/themes/seoulbones_light_bright.json"),
    THEME("extras/vscode/themes/seoulbones_light_default.json"),
    THEME("extras/vscode/themes/seoulbones_light_dim.json"),
    THEME("extras/vscode/themes/tokyobones_light_bright.json"),
    THEME("extras/vscode/themes/tokyobones_light_default.json"),
    THEME("extras/vscode/themes/tokyobones_light_dim.json"),
    THEME("extras/vscode/themes/vimbones_bright.json"),
    THEME("extras/vscode/themes/vimbones_default.json"),
    THEME("extras/vscode/themes/vimbones_dim.json"),
    THEME("extras/vscode/themes/zenwritten_light_bright.json"),
    THEME("extras/vscode/themes/zenwritten_light_default.json"),
    THEME("extras/vscode/themes/zenwritten_light_dim.json"),
};

fn THEME(comptime file_path: []const u8) theme_file {
    @setEvalBranchQuota(10000);
    return .{ .file_name = std.fs.path.basename(file_path), .json = @embedFile(file_path) };
}
